"""add_kyc_and_transaction_features

Revision ID: 865b133bdac8
Revises: 79e081e1324f
Create Date: 2025-10-19 05:57:25.611534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '865b133bdac8'
down_revision: Union[str, Sequence[str], None] = '79e081e1324f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ✅ KEEP deposits table - REMOVE the drop table commands
    
    # Add user_id to transactions with proper foreign key
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'])
    
    # Add KYC fields to users
    op.add_column('users', sa.Column('kyc_submitted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('kyc_rejection_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('id_document_front', sa.String(), nullable=True))
    op.add_column('users', sa.Column('id_document_back', sa.String(), nullable=True))
    op.add_column('users', sa.Column('proof_of_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('selfie_photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove KYC fields from users
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'country')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'selfie_photo')
    op.drop_column('users', 'proof_of_address')
    op.drop_column('users', 'id_document_back')
    op.drop_column('users', 'id_document_front')
    op.drop_column('users', 'kyc_rejection_reason')
    op.drop_column('users', 'kyc_submitted_at')
    
    # Remove user_id from transactions
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_id')
    
    # ✅ KEEP deposits table - REMOVE the create table commands for deposits
    
    # ### end Alembic commands ###