"""add_marqeta_cards_trading_multi_currency

Revision ID: cd7a4ebded16
Revises: 865b133bdac8
Create Date: 2025-10-19 13:15:37.175224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7a4ebded16'
down_revision: Union[str, Sequence[str], None] = '865b133bdac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create trading_bots table
    op.create_table('trading_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=True),
    sa.Column('current_profit_cents', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('total_profit_cents', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create trades table
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('profit_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['trading_bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Add new columns to cards table for Marqeta integration
    op.add_column('cards', sa.Column('marqeta_card_token', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('marqeta_user_token', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('card_program', sa.String(), server_default='elite_premium', nullable=True))
    op.add_column('cards', sa.Column('balance_cents', sa.BigInteger(), server_default='0', nullable=True))
    op.add_column('cards', sa.Column('currency', sa.String(), server_default='USD', nullable=True))
    op.add_column('cards', sa.Column('status', sa.String(), server_default='active', nullable=True))
    op.add_column('cards', sa.Column('card_type', sa.String(), server_default='virtual', nullable=True))
    op.add_column('cards', sa.Column('provider', sa.String(), server_default='marqeta', nullable=True))
    op.add_column('cards', sa.Column('linked_to_vault', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('cards', sa.Column('vault_funding_enabled', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('cards', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('cards', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    
    # Create indexes for better performance
    op.create_index(op.f('ix_cards_marqeta_card_token'), 'cards', ['marqeta_card_token'], unique=True)
    op.create_index(op.f('ix_trading_bots_user_id'), 'trading_bots', ['user_id'], unique=False)
    op.create_index(op.f('ix_trades_bot_id'), 'trades', ['bot_id'], unique=False)
    
    # Update existing cards with default values
    op.execute("UPDATE cards SET balance_cents = 0")
    op.execute("UPDATE cards SET currency = 'USD'")
    op.execute("UPDATE cards SET status = 'active'")
    op.execute("UPDATE cards SET card_type = 'virtual'")
    op.execute("UPDATE cards SET provider = 'marqeta'")
    op.execute("UPDATE cards SET linked_to_vault = true")
    op.execute("UPDATE cards SET vault_funding_enabled = true")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index(op.f('ix_trades_bot_id'), table_name='trades')
    op.drop_index(op.f('ix_trading_bots_user_id'), table_name='trading_bots')
    op.drop_index(op.f('ix_cards_marqeta_card_token'), table_name='cards')
    
    # Drop new columns from cards table
    op.drop_column('cards', 'updated_at')
    op.drop_column('cards', 'created_at')
    op.drop_column('cards', 'vault_funding_enabled')
    op.drop_column('cards', 'linked_to_vault')
    op.drop_column('cards', 'provider')
    op.drop_column('cards', 'card_type')
    op.drop_column('cards', 'status')
    op.drop_column('cards', 'currency')
    op.drop_column('cards', 'balance_cents')
    op.drop_column('cards', 'card_program')
    op.drop_column('cards', 'marqeta_user_token')
    op.drop_column('cards', 'marqeta_card_token')
    
    # Drop tables
    op.drop_table('trades')
    op.drop_table('trading_bots')
    
    # ### end Alembic commands ###